### ISSUE TITLE
Possible inversion of operations in calculation of admissibility loss 

### ISSUE THREAD

**Issue by CharlesGaydon** [ekalinicheva/plot_vegetation_coverage#1]
https://github.com/ekalinicheva/plot_vegetation_coverage/blob/f703325542e1241694acf1a7fac712ab636a450c/model/loss_functions.py#L63

This loss functions looks a lot like a RMSE, except that the root-squaring is performed after averaging instead of before. In this case, pow(2) and pow(0.5) would cancel each other. Is it possible that this operation should look like this instead :

`((pred_adm - gt_adm[:, -1]).pow(2) + 0.0001).mean().pow(0.5)`

? 
This is probably not a big deal since admissibility loss is usually not considered at the moment, but I felt better to share my observation !

**Comment by ekalinicheva** [comment]
Everything is fine with this formula! It's an absolute loss error and as we add epsilon=0.0001 pow(2) and pow(0.5) do not cancel each other.

**Comment by CharlesGaydon** [comment]
All right, thanks for claryfing :+1:
Closing the issue.
